# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: hetzner-api-key
#   namespace: cert-manager
# spec:
#   refreshInterval: 600
#   secretStoreRef:
#     # This name must match the metadata.name in the `SecretStore`
#     name: bitwarden-secretsmanager
#     kind: ClusterSecretStore
#   target:
#     name: hetzner-api-key
#   data:
#     - secretKey: api-key
#       remoteRef:
#         key: "FILL IN"
