apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-secrets-manager
  namespace: argocd
spec:
  project: default
  sources:
    # Helm Chart aus dem Internet
    - repoURL: https://charts.bitwarden.com
      chart: sm-operator
      targetRevision: 2.0.3
      helm:
        valueFiles:
          - $values/platform/bitwarden-secrets-manager/values.yaml
          - $values/platform/bitwarden-secrets-manager/values-dev.yaml
    # Git-Repository mit den Values
    - repoURL: https://github.com:/kblase/vielsam-homelab.git
      targetRevision: dev
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden-secrets-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
