apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  sources:
    # Helm Chart aus dem Internet
    - repoURL: https://raw.githubusercontent.com/truenas/truenas-csi/master/charts
      chart: truenas-csi
      targetRevision: 1.3.0
      helm:
        valueFiles:
          - $values/platform/truenas-csi/values.yaml
    # Git-Repository mit den Values
    - repoURL: https://github.com:/kblase/vielsam-homelab.git
      targetRevision: dev
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
