apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd

spec:
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
