apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
  namespace: argocd
spec:
  organizationId: {{ .Values.organizationId }}
  secretName: bw-sample-secret
  onlyMappedSecrets: true # default is true
  map:
    - bwSecretId: "6d527c8d-2ee7-457d-8b3c-b4c701629514"
      secretKeyName: "test-secret"
#  - bwSecretId: d132a5ed-12bd-49af-9b74-b11b01025d58
#     secretKeyName: test__secret__2
  authToken:
    secretName: bw-auth-token
    secretKey: token
